### PR TITLE
Add support for uploading without actually having a physical file

### PR DESCRIPTION
**Pull request by logiclrd**
I have no easy way to test this... yet. I am working on some code that will eventually be integrated with B2. But, I need this functionality -- the ability to upload a file without that file being an _actual physical file_ on the client side at the time of the upload.

### CODE REVIEW

**Comment by microcompiler** [comment]
@logiclrd thank you for all of your contributions.  My apologies that it took me so long to get them merged in.

**Comment by logiclrd** [comment]
@microcompiler I had reached a point where I thought the project was abandoned, and resigned myself to maintaining my own fork of it. Looks like I don't need to do that after all! :-) Thanks!

**Comment by logiclrd** [comment]
@microcompiler I have made PRs for a few additional changes that were in the fork.

**Comment by logiclrd** [comment]
@microcompiler Have you seen the PRs? If not, is there some way I can reach out to you if/when changes are proposed?

**Pull request merged**
